name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: [ubuntu-latest, windows-2022, macos-12, macos-13]

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: gcc -std=c11 -Wall -Wextra -Wpedantic -Werror example.c elapsed.c -o example
    - name: test
      run: ./example
