name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: gcc -std=c11 -Wall -Wextra -Wpedantic -Werror example.c elapsed.c -o example
    - name: test
      run: ./example
