name: Test

on: push

jobs:
  test:
    name: Test on ${{ matrix.os }} with build type ${{ matrix.build_type }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, macos-12, macos-11, windows-latest]
        build_type: [Release, Debug]

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        if: runner.os == 'Linux'
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DUSE_SANITIZER='Address;Undefined' -DENABLE_ALL_WARNINGS=ON

      - name: Configure CMake
        if: runner.os != 'Linux'
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DENABLE_ALL_WARNINGS=ON

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
