name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-on-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: gcc -std=c11 -Wall -Wextra -Wpedantic -Werror example.c elapsed.c -o example
    - name: test
      run: ./example


  build-on-mac:

    runs-on: mac-13

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: gcc -std=c11 -Wall -Wextra -Wpedantic -Werror example.c elapsed.c -o example
    - name: test
      run: ./example


  build-on-windows:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: gcc -std=c11 -Wall -Wextra -Wpedantic -Werror example.c elapsed.c -o example
    - name: test
      run: ./example

